name: dropsonde_test 
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ca-certificates
  - certifi
  - ipython
  - metpy
  - myst-parser
  - numpy
  - nbsphinx
  - netcdf4
  - openssl
  - pre-commit
  - sphinx
  - sphinx-autobuild
  - xarray
  - pip
  - pip:
    - sphinx-autodoc2
    - sphinx-book-theme
    - sphinx-last-updated-by-git
    - git+https://github.com/atmdrops/pydropsonde.git#egg=pydropsonde 
